"""Add plot table

Revision ID: 172161496b11
Revises: 68739c1255ec
Create Date: 2025-05-13 21:14:38.342888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172161496b11'
down_revision = '68739c1255ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('item', sa.String(length=64), nullable=False),
    sa.Column('quantity_used', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=64), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('stocks')
    op.drop_table('users')
    op.drop_table('inventory_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=64), nullable=False),
    sa.Column('item', sa.VARCHAR(length=64), nullable=False),
    sa.Column('quantity_used', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('role', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('stocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item', sa.VARCHAR(length=64), nullable=False),
    sa.Column('stock', sa.INTEGER(), nullable=False),
    sa.Column('used', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item')
    )
    op.drop_table('user')
    op.drop_table('stock')
    op.drop_table('inventory_log')
    # ### end Alembic commands ###
