"""Add plot table

Revision ID: 68739c1255ec
Revises: 
Create Date: 2025-05-13 20:47:59.822080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68739c1255ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plot_number', sa.Integer(), nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plot_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plot')
    # ### end Alembic commands ###
