"""Add row and col to Plot

Revision ID: 78f7539484eb
Revises: 172161496b11
Create Date: 2025-06-18 21:19:11.068062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f7539484eb'
down_revision = '172161496b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('row', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('col', sa.Integer(), nullable=True))
        batch_op.alter_column('plot_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('plot_number',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('col')
        batch_op.drop_column('row')

    # ### end Alembic commands ###
